name: Deploy to AWS via CDK

on:
  workflow_dispatch:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::496462056073:role/GitHubActionsDeployRole
          aws-region: us-west-2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          pip install -r requirements.txt

      - name: CDK Deploy
        run: cdk deploy --require-approval never
